### List live inputs
GET https://api.cloudflare.com/client/v4/accounts/{{CF-ACCOUNT}}/stream/live_inputs
Authorization: Bearer {{CF-TOKEN}}

### Retrieve a live input
GET https://api.cloudflare.com/client/v4/accounts/{{CF-ACCOUNT}}/stream/live_inputs/$LIVE_INPUT_IDENTIFIER
Authorization: Bearer {{CF-TOKEN}}

### Create a live input
POST https://api.cloudflare.com/client/v4/accounts/{{CF-ACCOUNT}}/stream/live_inputs
Authorization: Bearer {{CF-TOKEN}}
Content-Type: application/json

{
  "deleteRecordingAfterDays": 45,
  "enabled": true,
  "meta": {
    "name": "test stream 1"
  },
  "recording": {
    "hideLiveViewerCount": false,
    "mode": "off",
    "requireSignedURLs": false,
    "timeoutSeconds": 0
  }
}


### Update a live input
PUT https://api.cloudflare.com/client/v4/accounts/{{CF-ACCOUNT}}/stream/live_inputs/$LIVE_INPUT_IDENTIFIER
Authorization: Bearer {{CF-TOKEN}}
Content-Type: application/json

{
  "deleteRecordingAfterDays": 45,
  "enabled": true,
  "meta": {
    "name": "test stream 1"
  },
  "recording": {
    "hideLiveViewerCount": false,
    "mode": "off",
    "requireSignedURLs": false,
    "timeoutSeconds": 0
  }
}

### Delete a live input
< {%
    request.variables.set("clients", [ // test data
        {LIVE_INPUT_IDENTIFIER:'f9cf138*******************a7a99d'},
        {LIVE_INPUT_IDENTIFIER:'07964d8*******************f15e3f'},
        {LIVE_INPUT_IDENTIFIER:'e902cd0*******************ab3a2e'},
        {LIVE_INPUT_IDENTIFIER:'9851a67*******************da6d41'},
    ])
%}
DELETE https://api.cloudflare.com/client/v4/accounts/{{CF-ACCOUNT}}/stream/live_inputs/{{$.clients..LIVE_INPUT_IDENTIFIER}}
Authorization: Bearer {{CF-TOKEN}}